// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: hello.proto

package hello

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Tester_SayHello_FullMethodName  = "/hello.Tester/SayHello"
	Tester_SayHello2_FullMethodName = "/hello.Tester/SayHello2"
	Tester_SayHello3_FullMethodName = "/hello.Tester/SayHello3"
	Tester_SayHello4_FullMethodName = "/hello.Tester/SayHello4"
)

// TesterClient is the client API for Tester service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TesterClient interface {
	SayHello(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloResp, error)
	SayHello2(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HelloResp], error)
	SayHello3(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[HelloReq, HelloResp], error)
	SayHello4(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HelloReq, HelloResp], error)
}

type testerClient struct {
	cc grpc.ClientConnInterface
}

func NewTesterClient(cc grpc.ClientConnInterface) TesterClient {
	return &testerClient{cc}
}

func (c *testerClient) SayHello(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloResp)
	err := c.cc.Invoke(ctx, Tester_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testerClient) SayHello2(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HelloResp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Tester_ServiceDesc.Streams[0], Tester_SayHello2_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HelloReq, HelloResp]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tester_SayHello2Client = grpc.ServerStreamingClient[HelloResp]

func (c *testerClient) SayHello3(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[HelloReq, HelloResp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Tester_ServiceDesc.Streams[1], Tester_SayHello3_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HelloReq, HelloResp]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tester_SayHello3Client = grpc.ClientStreamingClient[HelloReq, HelloResp]

func (c *testerClient) SayHello4(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HelloReq, HelloResp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Tester_ServiceDesc.Streams[2], Tester_SayHello4_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HelloReq, HelloResp]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tester_SayHello4Client = grpc.BidiStreamingClient[HelloReq, HelloResp]

// TesterServer is the server API for Tester service.
// All implementations must embed UnimplementedTesterServer
// for forward compatibility.
type TesterServer interface {
	SayHello(context.Context, *HelloReq) (*HelloResp, error)
	SayHello2(*HelloReq, grpc.ServerStreamingServer[HelloResp]) error
	SayHello3(grpc.ClientStreamingServer[HelloReq, HelloResp]) error
	SayHello4(grpc.BidiStreamingServer[HelloReq, HelloResp]) error
	mustEmbedUnimplementedTesterServer()
}

// UnimplementedTesterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTesterServer struct{}

func (UnimplementedTesterServer) SayHello(context.Context, *HelloReq) (*HelloResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedTesterServer) SayHello2(*HelloReq, grpc.ServerStreamingServer[HelloResp]) error {
	return status.Errorf(codes.Unimplemented, "method SayHello2 not implemented")
}
func (UnimplementedTesterServer) SayHello3(grpc.ClientStreamingServer[HelloReq, HelloResp]) error {
	return status.Errorf(codes.Unimplemented, "method SayHello3 not implemented")
}
func (UnimplementedTesterServer) SayHello4(grpc.BidiStreamingServer[HelloReq, HelloResp]) error {
	return status.Errorf(codes.Unimplemented, "method SayHello4 not implemented")
}
func (UnimplementedTesterServer) mustEmbedUnimplementedTesterServer() {}
func (UnimplementedTesterServer) testEmbeddedByValue()                {}

// UnsafeTesterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TesterServer will
// result in compilation errors.
type UnsafeTesterServer interface {
	mustEmbedUnimplementedTesterServer()
}

func RegisterTesterServer(s grpc.ServiceRegistrar, srv TesterServer) {
	// If the following call pancis, it indicates UnimplementedTesterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Tester_ServiceDesc, srv)
}

func _Tester_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TesterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tester_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TesterServer).SayHello(ctx, req.(*HelloReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tester_SayHello2_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TesterServer).SayHello2(m, &grpc.GenericServerStream[HelloReq, HelloResp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tester_SayHello2Server = grpc.ServerStreamingServer[HelloResp]

func _Tester_SayHello3_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TesterServer).SayHello3(&grpc.GenericServerStream[HelloReq, HelloResp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tester_SayHello3Server = grpc.ClientStreamingServer[HelloReq, HelloResp]

func _Tester_SayHello4_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TesterServer).SayHello4(&grpc.GenericServerStream[HelloReq, HelloResp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tester_SayHello4Server = grpc.BidiStreamingServer[HelloReq, HelloResp]

// Tester_ServiceDesc is the grpc.ServiceDesc for Tester service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tester_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hello.Tester",
	HandlerType: (*TesterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Tester_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SayHello2",
			Handler:       _Tester_SayHello2_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SayHello3",
			Handler:       _Tester_SayHello3_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SayHello4",
			Handler:       _Tester_SayHello4_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "hello.proto",
}
