# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import hello_pb2 as hello__pb2


class TesterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/hello.Tester/SayHello',
                request_serializer=hello__pb2.HelloReq.SerializeToString,
                response_deserializer=hello__pb2.HelloResp.FromString,
                )
        self.SayHello2 = channel.unary_stream(
                '/hello.Tester/SayHello2',
                request_serializer=hello__pb2.HelloReq.SerializeToString,
                response_deserializer=hello__pb2.HelloResp.FromString,
                )
        self.SayHello3 = channel.stream_unary(
                '/hello.Tester/SayHello3',
                request_serializer=hello__pb2.HelloReq.SerializeToString,
                response_deserializer=hello__pb2.HelloResp.FromString,
                )
        self.SayHello4 = channel.stream_stream(
                '/hello.Tester/SayHello4',
                request_serializer=hello__pb2.HelloReq.SerializeToString,
                response_deserializer=hello__pb2.HelloResp.FromString,
                )


class TesterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SayHello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayHello2(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayHello3(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayHello4(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TesterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=hello__pb2.HelloReq.FromString,
                    response_serializer=hello__pb2.HelloResp.SerializeToString,
            ),
            'SayHello2': grpc.unary_stream_rpc_method_handler(
                    servicer.SayHello2,
                    request_deserializer=hello__pb2.HelloReq.FromString,
                    response_serializer=hello__pb2.HelloResp.SerializeToString,
            ),
            'SayHello3': grpc.stream_unary_rpc_method_handler(
                    servicer.SayHello3,
                    request_deserializer=hello__pb2.HelloReq.FromString,
                    response_serializer=hello__pb2.HelloResp.SerializeToString,
            ),
            'SayHello4': grpc.stream_stream_rpc_method_handler(
                    servicer.SayHello4,
                    request_deserializer=hello__pb2.HelloReq.FromString,
                    response_serializer=hello__pb2.HelloResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hello.Tester', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Tester(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hello.Tester/SayHello',
            hello__pb2.HelloReq.SerializeToString,
            hello__pb2.HelloResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SayHello2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/hello.Tester/SayHello2',
            hello__pb2.HelloReq.SerializeToString,
            hello__pb2.HelloResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SayHello3(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/hello.Tester/SayHello3',
            hello__pb2.HelloReq.SerializeToString,
            hello__pb2.HelloResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SayHello4(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/hello.Tester/SayHello4',
            hello__pb2.HelloReq.SerializeToString,
            hello__pb2.HelloResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
